// action types
export const CATEGORY_ADD =     'CATEGORY_ADD'
export const CATEGORY_UPDATE =  'CATEGORY_UPDATE'
export const CATEGORY_SORT =    'CATEGORY_SORT'
export const CATEGORY_DELETE =  'CATEGORY_DELETE'

export const BUDGET_DISABLE = 'BUDGET_DISABLE'
export const BUDGET_UPDATE =  'BUDGET_UPDATE'

export const EXPENSE_ADD =     'EXPENSE_ADD'
export const EXPENSE_UPDATE =  'EXPENSE_UPDATE'
export const EXPENSE_DELETE =  'EXPENSE_DELETE'
